// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"goaws/internal"
)

// Injectors from wire.go:

func InitializeDatabase() (goaws.DatabaseConnection, error) {
	databaseConnectionConfig, err := goaws.ProvideConfig()
	if err != nil {
		return goaws.DatabaseConnection{}, err
	}
	databaseConnection, err := goaws.ProvideDatabase(databaseConnectionConfig)
	if err != nil {
		return goaws.DatabaseConnection{}, err
	}
	return databaseConnection, nil
}
